---
title: "Datatable Testing"
output: html_document
date: '2022-07-27'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(DT)
library(dplyr)

df_to_js <- function(x, var_name = "data", ...){
  
  json_data <- jsonlite::toJSON(x, ...)
  
  htmltools::tags$script(paste0("var ",var_name," = ", json_data, ";"))
}

testData = read.csv("testdata.csv")



```

```{r data-script-tag,  echo=FALSE}
df_to_js(testData, "testData")
```

```{js testing, echo=FALSE}
// var table = $(".html-widget-static-bound").DataTable();

// console.log(table.rows().data())

var filteredData;


```


# Testing if possible to grab data from an R datatable

```{r cars, echo=FALSE}
DT::datatable(testData, filter = "top", rownames = TRUE,
              callback = JS("
                            table.on('search.dt', function() {
                              searched_data = table.rows( { search: 'applied' } ).data()
                              //console.log(searched_data.length);
                            newIndexes = []
                            for (var i= 0; i < searched_data.length; i++) {
                              newIndexes.push(searched_data[i][0] - 1)
                            }
                            
                              //newData = []
                            //  for (var i = 0; i < searched_data.length; i++) {
                            //      newData.push(searched_data[i])
                            //  }
                              console.log(newIndexes)
                            // at this point data would go into a new render of plot
                            
                            filteredData = testData.filter((d,i) => newIndexes.indexOf(i) != -1);
                            console.log(filteredData)
                            
                            
                            });
                            
                            // This will filter out data based on index of returned values
                            // var filteredData = testData.filter((d, i) => indexList.indexOf(i) != -1)
                            
                            return table;
                            "))
```




